Wesleyeduardo bitbucket
decioluckow/divulgit pull request #29
Opened 2022-07-22 00:33 UTC by wesleyeduardocr7

2022-08-05 21:11 UTC, decioluckow requested changes

2022-08-10 21:54 UTC, wesleyeduardocr7 commented on divulgit-app/src/main/resources/templates/login.html
> +                    <option value='{"askUrl":"false", "askUsername":"true", "url":"api.bitbucket.org/2.0", "plataform":"BITBUCKET"}'>Bitbucket Cloud</option>
#feito

2022-08-10 21:54 UTC, wesleyeduardocr7 commented on divulgit-remote-bitbucket/pom.xml
> +    <properties>
#feito

2022-08-10 21:54 UTC, wesleyeduardocr7 commented on divulgit-remote-bitbucket/pom.xml
> +            <version>0.0.2-SNAPSHOT</version>
#feito

2022-08-10 21:54 UTC, wesleyeduardocr7 commented on divulgit-app/src/main/resources/templates/login.html
> +                    <option value='{"askUrl":"false", "askUsername":"true", "url":"api.bitbucket.org/2.0", "plataform":"BITBUCKET"}'>Bitbucket Cloud</option>
#feito

2022-08-10 21:54 UTC, wesleyeduardocr7 commented on divulgit-remote-bitbucket/src/test/java/org/divulgit/bitbucket/util/LinkHeaderUtilTest.java
> +    	ResponseEntity<String> response = ResponseEntity.noContent().header("Link", "<https://api.github.com/user/repos?per_page=2&page=2>; rel=\"prev\", <https://api.github.com/user/repos?per_page=2&pa
#feito

2022-08-10 21:55 UTC, wesleyeduardocr7 commented on divulgit-service/src/main/java/org/divulgit/service/remote/RemoteService.java
> +        ensureRegistred("api.bitbucket.org/2.0", RemoteType.BITBUCKET);
#feito

2022-08-11 02:02 UTC, decioluckow approved these changes

2022-08-11 02:02 UTC, merged