Ajuste nas regras do botão reload merge requests
decioluckow/divulgit pull request #51
Opened 2022-08-20 18:05 UTC by wesleyeduardocr7

2022-08-20 22:02 UTC, decioluckow requested changes

2022-08-20 23:50 UTC, wesleyeduardocr7 commented on divulgit-util/src/main/java/org/divulgit/util/URLUtil.java
> +    public String concatIds(List<Integer> values){
#feito

2022-08-21 00:05 UTC, wesleyeduardocr7 commented on divulgit-task/src/main/java/org/divulgit/task/mergerequest/MergeRequestIdsRemoteScan.java
> +            List<RemoteMergeRequest> mergeRequests = new ArrayList<>(remoteMergeRequests);
#feito

2022-08-21 00:06 UTC, wesleyeduardocr7 commented on divulgit-remote-gitlab/src/main/java/org/divulgit/gitlab/GitLabCallerFacade.java
> +        return mergeRequestCaller.retrieveMergeRequests(remote,project,requestedMergeRequestExternalIds,authentication);
#feito

2022-08-21 00:06 UTC, wesleyeduardocr7 commented on divulgit-remote-bitbucket/src/main/java/org/divulgit/bitbucket/BitBucketCallerFacade.java
> +        return bitBucketPullRequestsCaller.retrievePullRequests(remote,user,project,requestedMergeRequestExternalIds,authentication);
#feito

2022-08-21 00:09 UTC, wesleyeduardocr7 commented on divulgit-remote-azure/src/main/java/org/divulgit/azure/AzureCallerFacade.java
> +        return pullRequestService.retrievePullRequests(remote,user,project,requestedMergeRequestExternalIds,authentication);
#feito

2022-08-21 00:11 UTC, wesleyeduardocr7 commented on divulgit-app/src/main/resources/templates/mergeRequests.html
> +            if(response.status >= 400 && response.status < 600){
#feito

2022-08-21 20:47 UTC, decioluckow approved these changes

2022-08-21 20:48 UTC, merged