Divulgit 04
decioluckow/divulgit pull request #53
Opened 2022-08-26 19:33 UTC by wesleyeduardocr7

2022-08-26 19:43 UTC, decioluckow requested changes

2022-08-26 19:43 UTC, decioluckow commented on divulgit-service/src/main/java/org/divulgit/service/project/ProjectCommentsService.java
> +            if(Objects.nonNull(project.getLastScan())){
formatacao

2022-08-26 19:43 UTC, decioluckow commented on divulgit-service/src/main/java/org/divulgit/service/project/ProjectCommentsService.java
> +
espaço desnecessário

2022-08-26 19:43 UTC, decioluckow commented on divulgit-service/src/main/java/org/divulgit/service/project/ProjectCommentsService.java
> +
espaço desnecessario

2022-08-26 19:48 UTC, wesleyeduardocr7 commented on divulgit-service/src/main/java/org/divulgit/service/project/ProjectCommentsService.java
> +            if(Objects.nonNull(project.getLastScan())){
feito

2022-08-26 19:48 UTC, wesleyeduardocr7 commented on divulgit-service/src/main/java/org/divulgit/service/project/ProjectCommentsService.java
> +
feito

2022-08-26 19:48 UTC, wesleyeduardocr7 commented on divulgit-service/src/main/java/org/divulgit/service/project/ProjectCommentsService.java
> +
feito

2022-08-27 23:21 UTC, decioluckow approved these changes

2022-08-27 23:21 UTC, merged