DIVULGIT-62 - Criação de estrutura para testes integrados
decioluckow/divulgit pull request #63
Opened 2022-09-02 11:49 UTC by decioluckow

2022-09-02 16:32 UTC, wesleyeduardocr7 approved these changes

2022-09-09 12:33 UTC, giorgyismael requested changes
review realizado.

2022-09-09 12:33 UTC, giorgyismael commented on divulgit-remote-gitlab/src/main/java/org/divulgit/gitlab/mergerequest/LastMergeRequestCaller.java
> -            if (! remoteMergeRequests.isEmpty()) {
Uma sugestão é utilizar o CollectionUtils.isNotEmpty(remoteMergeRequests), então não é preciso negar uma afirmação, visto que o próprio nome do método se encarrega disso.

2022-09-09 12:33 UTC, giorgyismael commented on divulgit-remote-gitlab/src/main/java/org/divulgit/gitlab/error/GitLabErrorResponseHandler.java
> +        return response.getStatusCodeValue() != 200;
sugiro substituir o 200, por HttpStatus.OK

2022-09-09 12:35 UTC, decioluckow commented on divulgit-remote-gitlab/src/main/java/org/divulgit/gitlab/mergerequest/LastMergeRequestCaller.java
> -            if (! remoteMergeRequests.isEmpty()) {
#collections

2022-09-09 16:46 UTC, decioluckow commented on divulgit-remote-gitlab/src/main/java/org/divulgit/gitlab/mergerequest/LastMergeRequestCaller.java
> -            if (! remoteMergeRequests.isEmpty()) {
feito

2022-09-09 16:46 UTC, decioluckow commented on divulgit-remote-gitlab/src/main/java/org/divulgit/gitlab/error/GitLabErrorResponseHandler.java
> +        return response.getStatusCodeValue() != 200;
feito

2022-09-09 17:32 UTC, giorgyismael approved these changes

2022-09-09 17:33 UTC, giorgyismael approved these changes

2022-09-09 18:10 UTC, merged