Ajuste para ocultar botão de rescan MR com notificação em tela
decioluckow/divulgit pull request #65
Opened 2022-09-06 13:26 UTC by wesleyeduardocr7

2022-09-07 11:35 UTC, decioluckow requested changes

2022-09-07 11:35 UTC, decioluckow commented on divulgit-app/src/main/resources/templates/mergeRequests.html
> +        const toastElList = document.querySelectorAll('.toast')
Se vc analisar bem este codigo, vai perceber que ele está buscando todos os "toasts" da pagina para exibir, a gente não precisa disso, e se em algum momento utilizarmos mais um toast, ele também será exibido. Até mesmo o nome é muito generico. A ideia de usar o class para identificação é para identificar um grupo e não um componente individual. O mesmo class pode ser usado por vários componentes, o id é unico.

Por isso, devemos colocar um id no componente que o identifique com relação ao uso. O id do componente hoje é liveToast, que nao é um nome bom pra gente, o melhor seria : rescan-mergerequest-toast. .

Pra ter acesso a este componente diretamente vc pode usar o "var toastEl = document.getElementById(id)"
e a partir da variavel resultante dele fazer:
new bootstrap.Toast(toastEl).show()

2022-09-07 11:35 UTC, decioluckow commented on divulgit-app/src/main/resources/templates/mergeRequests.html
> +    function generateWarningRescanMergeRequest() {
Perguntei pra si mesmo o que faz o metodo "generateWarningRescanMergeRequest"? a resposta pronta seria: ele mostra o toast do reload do mergerequest... então porque não chama-lo desta forma?

showRescanMergeRequestToast

2022-09-07 21:52 UTC, wesleyeduardocr7 commented on divulgit-app/src/main/resources/templates/mergeRequests.html
> +            <a th:id="${mergeRequest.id}" href="javascript:void(0)" class="text-decoration-none mergerequest-reload" onclick="javascript:rescan(this)"><i class="bi bi-arrow-clockwise"></i></a>
feito

2022-09-07 21:53 UTC, wesleyeduardocr7 commented on divulgit-app/src/main/resources/templates/mergeRequests.html
> +                console.log(response)
feito

2022-09-07 21:53 UTC, wesleyeduardocr7 commented on divulgit-app/src/main/resources/templates/mergeRequests.html
> +        const toastElList = document.querySelectorAll('.toast')
feito

2022-09-07 21:54 UTC, wesleyeduardocr7 commented on divulgit-app/src/main/resources/templates/mergeRequests.html
> +    function generateWarningRescanMergeRequest() {
decidi remover esse método e deixar em uma so linha   new bootstrap.Toast(document.getElementById('rescan-mergerequest-toast')).show();

2022-09-08 02:41 UTC, decioluckow approved these changes

2022-09-08 02:41 UTC, merged